import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Comprehensive SAKERNAS classification database (Expanded from SAKERNAS Agustus 2025)
const SAKERNAS_DB = {
  lapanganUsaha: {
    // Category A: Pertanian, Kehutanan dan Perikanan
    "01111": "Pertanian Jagung - Kategori A",
    "01121": "Pertanian Padi Hibrida - Kategori A",
    "01122": "Pertanian Padi Inbrida - Kategori A",
    "01113": "Pertanian Kedelai - Kategori A",
    "01114": "Pertanian Kacang Tanah - Kategori A",
    "01131": "Pertanian Hortikultura Sayuran Daun - Kategori A",
    "01132": "Pertanian Hortikultura Buah - Kategori A",
    "01133": "Pertanian Hortikultura Sayuran Buah - Kategori A",
    "01134": "Pertanian Hortikultura Sayuran Umbi - Kategori A",
    "01136": "Pertanian Jamur - Kategori A",
    "01140": "Perkebunan Tebu - Kategori A",
    "01150": "Perkebunan Tembakau - Kategori A",
    "01193": "Pertanian Tanaman Bunga - Kategori A",
    "01210": "Pertanian Buah Anggur - Kategori A",
    "01220": "Pertanian Buah-Buahan Tropis dan Subtropis - Kategori A",
    "01261": "Perkebunan Buah Kelapa - Kategori A",
    "01262": "Perkebunan Buah Kelapa Sawit - Kategori A",
    "01270": "Pertanian Tanaman Untuk Bahan Minuman - Kategori A",
    "01281": "Perkebunan Lada - Kategori A",
    "01282": "Perkebunan Cengkeh - Kategori A",
    "01283": "Pertanian Cabai - Kategori A",
    "01291": "Perkebunan Karet dan Tanaman Penghasil Getah Lainnya - Kategori A",
    "01301": "Pertanian Tanaman Hias - Kategori A",
    "01411": "Pembibitan dan Budidaya Sapi Potong - Kategori A",
    "01412": "Pembibitan dan Budidaya Sapi Perah - Kategori A",
    "01420": "Peternakan Kuda dan Sejenisnya - Kategori A",
    "01441": "Pembibitan dan Budidaya Domba Potong - Kategori A",
    "01442": "Pembibitan dan Budidaya Kambing Potong - Kategori A",
    "01461": "Budidaya Ayam Ras Pedaging - Kategori A",
    "01462": "Budidaya Ayam Ras Petelur - Kategori A",
    "01464": "Budidaya Ayam Lokal dan Persilangannya - Kategori A",
    "01465": "Pembibitan Dan Budidaya Itik Dan/Atau Bebek - Kategori A",
    "03111": "Penangkapan Pisces/Ikan Bersirip di Laut - Kategori A",
    "03121": "Penangkapan Pisces/Ikan Bersirip di Perairan Darat - Kategori A",
    "03211": "Pembesaran Pisces/Ikan Bersirip Laut - Kategori A",
    "03221": "Pembesaran Ikan Air Tawar di Kolam - Kategori A",
    
    // Category B: Pertambangan dan Penggalian
    "05100": "Pertambangan Batu Bara - Kategori B",
    "06100": "Ekstraksi Minyak Bumi - Kategori B",
    "07100": "Pertambangan Bijih Besi - Kategori B",
    "08910": "Pertambangan Mineral Kimia dan Pupuk - Kategori B",
    
    // Category C: Industri Pengolahan
    "10110": "Industri Pengolahan dan Pengawetan Daging - Kategori C",
    "10120": "Industri Pengolahan dan Pengawetan Ikan - Kategori C",
    "10740": "Industri Mie dan Produk Sejenis - Kategori C",
    "10791": "Industri Kecap, Tauco dan Sejenisnya - Kategori C",
    "13111": "Industri Persiapan Serat Tekstil - Kategori C",
    "14101": "Industri Pakaian Jadi - Kategori C",
    "16101": "Industri Penggergajian Kayu - Kategori C",
    "24101": "Industri Besi dan Baja Dasar - Kategori C",
    "28111": "Industri Mesin Untuk Keperluan Umum - Kategori C",
    
    // Category D: Pengadaan Listrik, Gas
    "35101": "Pembangkitan Tenaga Listrik - Kategori D",
    "35201": "Transmisi Tenaga Listrik - Kategori D",
    "35301": "Distribusi Tenaga Listrik - Kategori D",
    
    // Category F: Konstruksi
    "41001": "Konstruksi Gedung Hunian - Kategori F",
    "41002": "Konstruksi Gedung Perkantoran - Kategori F",
    "42101": "Konstruksi Bangunan Sipil Jalan - Kategori F",
    "42102": "Konstruksi Bangunan Sipil Jembatan - Kategori F",
    "43211": "Instalasi Listrik - Kategori F",
    
    // Category G: Perdagangan Besar dan Eceran
    "45101": "Perdagangan Besar Mobil Baru - Kategori G",
    "45102": "Perdagangan Besar Mobil Bekas - Kategori G",
    "45103": "Perdagangan Eceran Mobil Baru - Kategori G",
    "45201": "Reparasi Mobil - Kategori G",
    "45401": "Perdagangan Besar Sepeda Motor Baru - Kategori G",
    "45403": "Perdagangan Eceran Sepeda Motor Baru - Kategori G",
    "46201": "Perdagangan Besar Padi dan Palawija - Kategori G",
    "46311": "Perdagangan Besar Beras - Kategori G",
    "46312": "Perdagangan Besar Buah-buahan - Kategori G",
    "46313": "Perdagangan Besar Sayuran - Kategori G",
    "47111": "Perdagangan Eceran Serba Ada dengan Luas Area Penjualan 5000 M2 atau Lebih - Kategori G",
    "47112": "Perdagangan Eceran Berbagai Macam Barang yang Utamanya Makanan, Minuman atau Tembakau di Minimarket - Kategori G",
    "47113": "Perdagangan Eceran Berbagai Macam Barang yang Utamanya Makanan, Minuman atau Tembakau di Toko Kelontong - Kategori G",
    "47191": "Perdagangan Eceran Berbagai Macam Barang yang Utamanya Makanan, Minuman atau Tembakau Lainnya - Kategori G",
    "47192": "Perdagangan Eceran Berbagai Macam Barang yang Utamanya Bukan Makanan, Minuman atau Tembakau - Kategori G",
    "47211": "Perdagangan Eceran Beras - Kategori G",
    "47212": "Perdagangan Eceran Buah-buahan - Kategori G",
    "47213": "Perdagangan Eceran Sayuran - Kategori G",
    "47221": "Perdagangan Eceran Daging Sapi dan Daging Sapi Olahan - Kategori G",
    "47222": "Perdagangan Eceran Daging Ayam dan Daging Ayam Olahan - Kategori G",
    "47241": "Perdagangan Eceran Minuman Beralkohol - Kategori G",
    "47242": "Perdagangan Eceran Minuman Non Alkohol Bukan Susu - Kategori G",
    "47243": "Perdagangan Eceran Rokok dan Tembakau - Kategori G",
    "47511": "Perdagangan Eceran Tekstil - Kategori G",
    "47512": "Perdagangan Eceran Pakaian - Kategori G",
    "47513": "Perdagangan Eceran Alas Kaki - Kategori G",
    "47591": "Perdagangan Eceran Furnitur - Kategori G",
    "47741": "Perdagangan Eceran Alat Fotografi - Kategori G",
    "47742": "Perdagangan Eceran Obat Farmasi untuk Manusia - Kategori G",
    "47811": "Perdagangan Eceran Kios di Pasar atau Los Pasar - Kategori G",
    "47812": "Perdagangan Eceran Kaki Lima - Kategori G",
    
    // Category H: Pengangkutan dan Pergudangan
    "49111": "Angkutan Rel Penumpang Jarak Jauh - Kategori H",
    "49210": "Angkutan Bus Bertrayek - Kategori H",
    "49220": "Angkutan Bus Tidak Bertrayek - Kategori H",
    "49311": "Angkutan Darat Dengan Taksimeter - Kategori H",
    "49312": "Angkutan Darat Dengan Menggunakan Aplikasi - Kategori H",
    "49410": "Angkutan Darat untuk Barang - Kategori H",
    "49510": "Angkutan Melalui Saluran Pipa - Kategori H",
    "50111": "Angkutan Laut Dalam Negeri Untuk Penumpang - Kategori H",
    "51101": "Angkutan Udara Berjadwal Untuk Penumpang - Kategori H",
    "52101": "Pergudangan dan Penyimpanan - Kategori H",
    "53200": "Aktivitas Pos dan Kurir - Kategori H",
    
    // Category I: Penyediaan Akomodasi dan Penyediaan Makan Minum
    "55101": "Hotel Bintang - Kategori I",
    "55102": "Hotel Melati - Kategori I",
    "55103": "Motel - Kategori I",
    "55201": "Penyediaan Akomodasi Jangka Pendek Lainnya - Kategori I",
    "56101": "Restoran - Kategori I",
    "56102": "Rumah Makan - Kategori I",
    "56103": "Warung Makan - Kategori I",
    "56211": "Jasa Boga untuk Suatu Event Tertentu - Kategori I",
    "56301": "Bar - Kategori I",
    
    // Category J: Informasi dan Komunikasi
    "58110": "Penerbitan Buku - Kategori J",
    "58120": "Penerbitan Direktori dan Mailing List - Kategori J",
    "58130": "Penerbitan Surat Kabar, Majalah dan Jurnal - Kategori J",
    "59110": "Aktivitas Produksi Film, Video dan Program Televisi - Kategori J",
    "60100": "Penyiaran Radio - Kategori J",
    "60200": "Penyiaran Program Televisi - Kategori J",
    "61100": "Aktivitas Telekomunikasi dengan Kabel - Kategori J",
    "61200": "Aktivitas Telekomunikasi Tanpa Kabel - Kategori J",
    "62010": "Aktivitas Pemrograman Komputer - Kategori J",
    "62020": "Aktivitas Konsultasi Komputer dan Manajemen Fasilitas Komputer - Kategori J",
    "63110": "Aktivitas Pengolahan Data, Hosting dan Kegiatan yang Berhubungan - Kategori J",
    
    // Category K: Aktivitas Keuangan dan Asuransi
    "64110": "Bank Sentral - Kategori K",
    "64191": "Bank Umum Milik Pemerintah - Kategori K",
    "64192": "Bank Umum Swasta Nasional - Kategori K",
    "64201": "Bank Perkreditan Rakyat - Kategori K",
    "64910": "Aktivitas Sewa Guna Usaha (Financial Leasing) - Kategori K",
    "65111": "Asuransi Jiwa - Kategori K",
    "66110": "Administrasi Pasar Keuangan - Kategori K",
    "66120": "Aktivitas Pialang Efek dan Perdagangan Efek - Kategori K",
    
    // Category M: Aktivitas Profesional, Ilmiah dan Teknis
    "69100": "Aktivitas Hukum - Kategori M",
    "69200": "Aktivitas Akuntansi, Pembukuan dan Audit, Konsultasi Perpajakan - Kategori M",
    "70100": "Aktivitas Kantor Pusat - Kategori M",
    "70200": "Aktivitas Konsultasi Manajemen - Kategori M",
    "71101": "Aktivitas Arsitektur - Kategori M",
    "71102": "Aktivitas Teknik dan Konsultasi Teknik - Kategori M",
    "72101": "Penelitian dan Pengembangan Ilmu Pengetahuan Alam - Kategori M",
    "73100": "Aktivitas Periklanan - Kategori M",
    "74100": "Aktivitas Desain Khusus - Kategori M",
    "74200": "Aktivitas Fotografi - Kategori M",
    
    // Category N: Aktivitas Penyewaan
    "77100": "Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Kendaraan Bermotor - Kategori N",
    "77210": "Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Barang Rekreasi dan Olahraga - Kategori N",
    "78100": "Aktivitas Penyediaan Tenaga Kerja - Kategori N",
    "79110": "Aktivitas Agen Perjalanan - Kategori N",
    "79120": "Aktivitas Operator Tur - Kategori N",
    "80100": "Aktivitas Keamanan Swasta - Kategori N",
    "81100": "Aktivitas Penyedia Gabungan Jasa Penunjang Fasilitas - Kategori N",
    "82110": "Aktivitas Penyedia Gabungan Jasa Administrasi Kantor - Kategori N",
    
    // Category O: Administrasi Pemerintahan
    "84111": "Lembaga Legislatif - Kategori O",
    "84112": "Penyelenggaraan Pemerintah Negara Dan Kesekretariatan Negara - Kategori O",
    "84220": "Pertahanan - Kategori O",
    "84230": "Kepolisian - Kategori O",
    "84300": "Jaminan Sosial Wajib - Kategori O",
    
    // Category P: Pendidikan
    "85111": "Pendidikan Anak Usia Dini Formal - Kategori P",
    "85121": "Pendidikan Taman Kanak-kanak Pemerintah - Kategori P",
    "85122": "Pendidikan Taman Kanak-kanak Swasta - Kategori P",
    "85211": "Pendidikan Dasar Pemerintah - Kategori P",
    "85212": "Pendidikan Dasar Swasta - Kategori P",
    "85221": "Pendidikan Menengah Pertama Pemerintah - Kategori P",
    "85222": "Pendidikan Menengah Pertama Swasta - Kategori P",
    "85301": "Pendidikan Menengah Atas Pemerintah - Kategori P",
    "85302": "Pendidikan Menengah Atas Swasta - Kategori P",
    "85303": "Pendidikan Menengah Kejuruan Pemerintah - Kategori P",
    "85304": "Pendidikan Menengah Kejuruan Swasta - Kategori P",
    "85411": "Pendidikan Tinggi Akademik Pemerintah - Kategori P",
    "85412": "Pendidikan Tinggi Vokasi Dan Profesi Pemerintah - Kategori P",
    "85421": "Pendidikan Tinggi Akademik Swasta - Kategori P",
    "85422": "Pendidikan Tinggi Vokasi Dan Profesi Swasta - Kategori P",
    "85491": "Pendidikan Olahraga Dan Rekreasi - Kategori P",
    "85492": "Pendidikan Kebudayaan - Kategori P",
    
    // Category Q: Aktivitas Kesehatan Manusia
    "86101": "Aktivitas Rumah Sakit Pemerintah - Kategori Q",
    "86102": "Aktivitas Puskesmas - Kategori Q",
    "86103": "Aktivitas Rumah Sakit Swasta - Kategori Q",
    "86104": "Aktivitas Klinik Pemerintah - Kategori Q",
    "86105": "Aktivitas Klinik Swasta - Kategori Q",
    "86201": "Aktivitas Praktik Dokter - Kategori Q",
    "86202": "Aktivitas Praktik Dokter Spesialis - Kategori Q",
    "86203": "Aktivitas Praktik Dokter Gigi - Kategori Q",
    "86901": "Aktivitas Pelayanan Kesehatan Yang Dilakukan Oleh Tenaga Kesehatan Selain Dokter - Kategori Q",
    "86902": "Aktivitas Pelayanan Kesehatan Tradisional - Kategori Q",
    "87100": "Aktivitas Sosial Di Dalam Panti - Kategori Q",
    "88101": "Aktivitas Sosial Tanpa Akomodasi Untuk Lanjut Usia dan Penyandang Disabilitas - Kategori Q",
    
    // Category R: Kesenian, Hiburan dan Rekreasi
    "90011": "Aktivitas Seni Pertunjukan - Kategori R",
    "91011": "Perpustakaan Dan Arsip Pemerintah - Kategori R",
    "91021": "Museum Yang Dikelola Pemerintah - Kategori R",
    "91031": "Taman Konservasi - Kategori R",
    "92000": "Aktivitas Perjudian Dan Pertaruhan - Kategori R",
    "93111": "Fasilitas Stadion - Kategori R",
    "93121": "Klub Sepak Bola - Kategori R",
    "93211": "Taman Rekreasi - Kategori R",
    "93291": "Klub Malam - Kategori R",
    "93292": "Karaoke - Kategori R",
    
    // Category S: Aktivitas Jasa Lainnya
    "94110": "Aktivitas Organisasi Bisnis Dan Pengusaha - Kategori S",
    "94200": "Aktivitas Organisasi Buruh - Kategori S",
    "94910": "Aktivitas Organisasi Keagamaan - Kategori S",
    "94920": "Aktivitas Organisasi Politik - Kategori S",
    "95110": "Reparasi Komputer dan Peralatan Sejenisnya - Kategori S",
    "95210": "Reparasi Alat-alat Elektronik Konsumen - Kategori S",
    "96111": "Aktivitas Pangkas Rambut - Kategori S",
    "96112": "Aktivitas Salon Kecantikan - Kategori S",
    "96121": "Rumah Pijat - Kategori S",
    "96200": "Aktivitas Penatu - Kategori S",
    
    // Category T: Aktivitas Rumah Tangga
    "97000": "Aktivitas Rumah Tangga Sebagai Pemberi Kerja - Kategori T",
    "98100": "Aktivitas Yang Menghasilkan Barang Oleh Rumah Tangga - Kategori T",
    
    // Category U: Badan Internasional
    "99000": "Aktivitas Badan Internasional - Kategori U",
  },
  
  jenisPekerjaan: {
    // Golongan 0: TNI dan POLRI
    "0111": "Perwira Markas Besar TNI - Golongan 0",
    "0112": "Perwira TNI Angkatan Darat - Golongan 0",
    "0113": "Perwira TNI Angkatan Laut - Golongan 0",
    "0114": "Perwira TNI Angkatan Udara - Golongan 0",
    "0210": "Perwira POLRI - Golongan 0",
    
    // Golongan 1: Manajer
    "1111": "Legislator - Golongan 1",
    "1112": "Kepala Pemerintahan dan Kepala Daerah - Golongan 1",
    "1113": "Pemimpin Adat dan Kepala Desa - Golongan 1",
    "1114": "Pejabat Senior Organisasi Peminat Khusus - Golongan 1",
    "1120": "Manajer Pelaksana, Komersial dan Lainnya - Golongan 1",
    "1211": "Manajer Keuangan - Golongan 1",
    "1212": "Manajer Personalia - Golongan 1",
    "1213": "Manajer Kebijakan dan Perencanaan - Golongan 1",
    "1219": "Manajer Usaha, Administrasi dan Komersial Lainnya - Golongan 1",
    "1221": "Manajer Penjualan dan Pemasaran - Golongan 1",
    "1222": "Manajer Periklanan dan Hubungan Masyarakat - Golongan 1",
    "1223": "Manajer Penelitian dan Pengembangan - Golongan 1",
    "1311": "Manajer Produksi Pertanian dan Kehutanan - Golongan 1",
    "1312": "Manajer Produksi Akuakultur dan Perikanan - Golongan 1",
    "1321": "Manajer Industri Pengolahan - Golongan 1",
    "1322": "Manajer Pertambangan - Golongan 1",
    "1323": "Manajer Konstruksi - Golongan 1",
    "1324": "Manajer Pasokan, Distribusi dan yang Berhubungan - Golongan 1",
    "1330": "Manajer Teknologi Informasi dan Komunikasi - Golongan 1",
    "1341": "Manajer Pengasuhan Anak - Golongan 1",
    "1342": "Manajer Pelayanan Kesehatan - Golongan 1",
    "1343": "Manajer Pelayanan Kesejahteraan Lanjut Usia - Golongan 1",
    "1344": "Manajer Pelayanan Kesejahteraan Sosial - Golongan 1",
    "1345": "Manajer Pendidikan - Golongan 1",
    "1346": "Manajer Cabang Lembaga Keuangan - Golongan 1",
    "1349": "Manajer Pelayanan Profesional Lainnya - Golongan 1",
    "1411": "Manajer Hotel - Golongan 1",
    "1412": "Manajer Restoran - Golongan 1",
    "1420": "Manajer Perdagangan Eceran dan Grosir - Golongan 1",
    "1431": "Manajer Pusat Olahraga, Hiburan dan Kebudayaan - Golongan 1",
    "1439": "Manajer Pelayanan Lainnya - Golongan 1",
    
    // Golongan 2: Profesional
    "2111": "Ahli Fisika Dan Astronomi - Golongan 2",
    "2112": "Ahli Meteorologi Dan Klimatologi - Golongan 2",
    "2113": "Ahli Kimia - Golongan 2",
    "2114": "Ahli Geologi Dan Geofisika - Golongan 2",
    "2120": "Ahli Matematika, Aktuaris dan Ahli Statistika - Golongan 2",
    "2131": "Ahli Biologi - Golongan 2",
    "2132": "Ahli Pertanian, Kehutanan dan Perikanan - Golongan 2",
    "2133": "Ahli Lingkungan - Golongan 2",
    "2141": "Ahli Teknik Industri dan Produksi - Golongan 2",
    "2142": "Ahli Teknik Sipil - Golongan 2",
    "2143": "Ahli Teknik Lingkungan - Golongan 2",
    "2144": "Ahli Teknik Mesin - Golongan 2",
    "2145": "Ahli Teknik Kimia - Golongan 2",
    "2146": "Ahli Teknik Pertambangan, Metalurgi dan yang Berhubungan - Golongan 2",
    "2149": "Ahli Teknik Lainnya - Golongan 2",
    "2151": "Ahli Teknik Elektro - Golongan 2",
    "2152": "Ahli Teknik Elektronika - Golongan 2",
    "2153": "Ahli Teknik Telekomunikasi - Golongan 2",
    "2161": "Arsitek Bangunan - Golongan 2",
    "2162": "Arsitek Lansekap - Golongan 2",
    "2163": "Desainer Produk dan Pakaian - Golongan 2",
    "2164": "Perencana Kota, Lalu Lintas dan Regional - Golongan 2",
    "2165": "Kartografer dan Surveyor - Golongan 2",
    "2166": "Desainer Grafis dan Multimedia - Golongan 2",
    "2211": "Dokter Umum - Golongan 2",
    "2212": "Dokter Spesialis - Golongan 2",
    "2221": "Dokter Perawat Profesional - Golongan 2",
    "2222": "Bidan Profesional - Golongan 2",
    "2230": "Dokter Pengobatan Tradisional dan Alternatif - Golongan 2",
    "2240": "Paramedis - Golongan 2",
    "2250": "Dokter Hewan - Golongan 2",
    "2261": "Dokter Gigi - Golongan 2",
    "2262": "Apoteker - Golongan 2",
    "2263": "Ahli Kesehatan dan Keselamatan Lingkungan - Golongan 2",
    "2264": "Ahli Gizi - Golongan 2",
    "2265": "Audiologis dan Logopedis - Golongan 2",
    "2269": "Ahli Kesehatan Lainnya - Golongan 2",
    "2310": "Guru Perguruan Tinggi - Golongan 2",
    "2320": "Guru Kejuruan - Golongan 2",
    "2330": "Guru Sekolah Menengah - Golongan 2",
    "2341": "Guru Sekolah Dasar - Golongan 2",
    "2342": "Guru Anak Usia Dini - Golongan 2",
    "2351": "Spesialis Pendidikan - Golongan 2",
    "2352": "Instruktur Kebutuhan Khusus - Golongan 2",
    "2353": "Guru Bahasa Lainnya - Golongan 2",
    "2354": "Guru Musik - Golongan 2",
    "2355": "Instruktur Teknologi Informasi - Golongan 2",
    "2356": "Guru Seni - Golongan 2",
    "2359": "Spesialis Pengajaran Lainnya - Golongan 2",
    "2411": "Akuntan - Golongan 2",
    "2412": "Konsultan Keuangan dan Investasi - Golongan 2",
    "2413": "Analis Keuangan - Golongan 2",
    "2421": "Analis Manajemen dan Organisasi - Golongan 2",
    "2422": "Ahli Kebijakan Administrasi - Golongan 2",
    "2423": "Ahli Manajemen Personalia dan Karir - Golongan 2",
    "2424": "Ahli Pelatihan dan Pengembangan Staf - Golongan 2",
    "2431": "Profesional Periklanan dan Pemasaran - Golongan 2",
    "2432": "Profesional Hubungan Masyarakat - Golongan 2",
    "2433": "Profesional Penjualan Teknis dan Medis - Golongan 2",
    "2434": "Profesional Teknologi Informasi dan Komunikasi - Golongan 2",
    "2511": "Analis Sistem - Golongan 2",
    "2512": "Pengembang Perangkat Lunak - Golongan 2",
    "2513": "Pengembang Web dan Multimedia - Golongan 2",
    "2514": "Pemrogram Aplikasi - Golongan 2",
    "2519": "Pengembang dan Analis Perangkat Lunak dan Multimedia Lainnya - Golongan 2",
    "2521": "Desainer dan Administrator Basis Data - Golongan 2",
    "2522": "Administrator Sistem - Golongan 2",
    "2523": "Administrator Jaringan Komputer - Golongan 2",
    "2529": "Profesional Basis Data dan Jaringan Lainnya - Golongan 2",
    "2611": "Pengacara - Golongan 2",
    "2612": "Hakim - Golongan 2",
    "2619": "Profesional Hukum Lainnya - Golongan 2",
    "2621": "Pustakawan dan yang Berhubungan - Golongan 2",
    "2622": "Arsiparis dan Kurator Museum - Golongan 2",
    "2631": "Ekonom - Golongan 2",
    "2632": "Sosiolog, Antropolog dan yang Berhubungan - Golongan 2",
    "2633": "Filsuf, Sejarawan dan Ahli Politik - Golongan 2",
    "2634": "Psikolog - Golongan 2",
    "2635": "Pekerja Sosial dan Konselor - Golongan 2",
    "2636": "Profesional Keagamaan - Golongan 2",
    "2641": "Penulis dan Editor - Golongan 2",
    "2642": "Jurnalis - Golongan 2",
    "2643": "Penerjemah, Interpreter dan Ahli Bahasa Lainnya - Golongan 2",
    "2651": "Seniman Seni Rupa - Golongan 2",
    "2652": "Musisi, Penyanyi dan Komposer - Golongan 2",
    "2653": "Penari dan Koreografer - Golongan 2",
    "2654": "Direktur Film, Teater dan yang Berhubungan - Golongan 2",
    "2655": "Aktor - Golongan 2",
    "2656": "Penyiar Radio, Televisi dan yang Berhubungan - Golongan 2",
    "2659": "Seniman Kreatif dan Penghibur Lainnya - Golongan 2",
    
    // Golongan 3: Teknisi dan Asisten Profesional
    "3111": "Teknisi Kimia - Golongan 3",
    "3112": "Teknisi Teknik Sipil - Golongan 3",
    "3113": "Teknisi Teknik Elektro - Golongan 3",
    "3114": "Teknisi Teknik Elektronika - Golongan 3",
    "3115": "Teknisi Teknik Mesin - Golongan 3",
    "3116": "Teknisi Teknik Kimia - Golongan 3",
    "3117": "Teknisi Pertambangan dan Metalurgi - Golongan 3",
    "3118": "Juru Gambar - Golongan 3",
    "3119": "Teknisi Fisika dan Teknik Lainnya - Golongan 3",
    "3121": "Supervisor Pertambangan - Golongan 3",
    "3122": "Supervisor Industri Pengolahan - Golongan 3",
    "3123": "Supervisor Konstruksi - Golongan 3",
    "3131": "Operator Instalasi Pembangkit Listrik - Golongan 3",
    "3132": "Operator Instalasi Pengolahan Sampah - Golongan 3",
    "3133": "Pengendali Instalasi Pengolahan Kimia - Golongan 3",
    "3134": "Operator Instalasi Pemurnian Minyak Bumi dan Gas Alam - Golongan 3",
    "3135": "Pengendali Proses Produksi Logam - Golongan 3",
    "3139": "Pengendali Proses Lainnya - Golongan 3",
    "3141": "Teknisi Ilmu Hayat - Golongan 3",
    "3142": "Teknisi Pertanian - Golongan 3",
    "3143": "Teknisi Kehutanan - Golongan 3",
    "3151": "Inspektur Keselamatan Kapal - Golongan 3",
    "3152": "Pengawas Kesehatan dan Keselamatan Kerja - Golongan 3",
    "3153": "Inspektur Kualitas Lingkungan - Golongan 3",
    "3154": "Pengendali Mutu Lainnya - Golongan 3",
    "3211": "Teknisi Peralatan Medis dan Gigi - Golongan 3",
    "3212": "Perawat (Vokasi) - Golongan 3",
    "3213": "Bidan (Vokasi) - Golongan 3",
    "3214": "Paramedis Darurat - Golongan 3",
    "3221": "Perawat Kesehatan Masyarakat - Golongan 3",
    "3222": "Perawat Kesehatan Profesional Lainnya - Golongan 3",
    "3230": "Praktisi Pengobatan Tradisional dan Alternatif - Golongan 3",
    "3240": "Teknisi Veteriner - Golongan 3",
    "3251": "Teknisi Gigi - Golongan 3",
    "3252": "Teknisi dan Asisten Laboratorium Medis - Golongan 3",
    "3253": "Teknisi Farmasi dan Asisten Farmasi - Golongan 3",
    "3254": "Protesa dan Ortotis - Golongan 3",
    "3255": "Teknisi Optik dan Optometris - Golongan 3",
    "3256": "Pekerja Fisioterapi dan yang Berhubungan - Golongan 3",
    "3257": "Teknisi dan Pekerja Kesehatan Lainnya - Golongan 3",
    "3311": "Pedagang Efek dan Perantara Penjualan - Golongan 3",
    "3312": "Agen Pinjaman - Golongan 3",
    "3313": "Agen Akunting - Golongan 3",
    "3314": "Agen Statistik, Keuangan dan Asuransi - Golongan 3",
    "3315": "Penilai dan Juru Taksir - Golongan 3",
    "3321": "Agen Asuransi - Golongan 3",
    "3322": "Agen Perdagangan - Golongan 3",
    "3323": "Agen Pembelian - Golongan 3",
    "3324": "Agen Pelayaran - Golongan 3",
    "3331": "Clearing Forwarding - Golongan 3",
    "3332": "Operator Konferensi dan Acara - Golongan 3",
    "3333": "Agen Pekerjaan dan Kontraktor Tenaga Kerja - Golongan 3",
    "3334": "Agen Real Estat - Golongan 3",
    "3339": "Agen Usaha, Pialang dan Perantara Perdagangan Lainnya - Golongan 3",
    "3341": "Supervisor Kantor - Golongan 3",
    "3342": "Paralegal dan Asisten Hukum - Golongan 3",
    "3343": "Agen Administrasi Pemerintah - Golongan 3",
    "3344": "Agen Pelayanan Sosial dan Agama - Golongan 3",
    "3351": "Teknisi Bea Cukai dan Pengawasan Perbatasan - Golongan 3",
    "3352": "Inspektur Pajak dan Pajak Daerah - Golongan 3",
    "3353": "Inspektur Perlindungan Sosial - Golongan 3",
    "3354": "Inspektur Perijinan dan Pengawasan Lainnya - Golongan 3",
    "3355": "Detektif Polisi dan Penyidik - Golongan 3",
    "3359": "Agen Pelayanan Pemerintah Lainnya - Golongan 3",
    "3411": "Asisten Hukum - Golongan 3",
    "3412": "Pekerja Sosial - Golongan 3",
    "3413": "Pekerja Kemasyarakatan - Golongan 3",
    "3421": "Atlet dan Olahragawan - Golongan 3",
    "3422": "Pelatih dan Instruktur Olahraga - Golongan 3",
    "3423": "Instruktur Kebugaran - Golongan 3",
    "3431": "Fotografer - Golongan 3",
    "3432": "Desainer dan Dekorator Interior - Golongan 3",
    "3433": "Teknisi Galeri, Museum dan Perpustakaan - Golongan 3",
    "3434": "Koki - Golongan 3",
    "3435": "Teknisi dan Operator Peralatan Broadcasting - Golongan 3",
    "3511": "Teknisi Operasi Teknologi Informasi dan Komunikasi - Golongan 3",
    "3512": "Teknisi Pengguna Pendukung Teknologi Informasi dan Komunikasi - Golongan 3",
    "3513": "Teknisi Jaringan Komputer dan Sistem - Golongan 3",
    "3514": "Teknisi Web - Golongan 3",
    "3521": "Operator Peralatan Penyiaran Audio Visual - Golongan 3",
    "3522": "Teknisi Peralatan Audio Visual - Golongan 3",
    
    // Golongan 4: Tenaga Tata Usaha
    "4110": "Tenaga Administrasi Perkantoran Umum - Golongan 4",
    "4120": "Sekretaris - Golongan 4",
    "4131": "Operator Mesin Pengetik dan Entri Data - Golongan 4",
    "4132": "Operator Mesin Pengolah Kata - Golongan 4",
    "4211": "Juru Catat dan Penanganan Uang - Golongan 4",
    "4212": "Pemegang Buku - Golongan 4",
    "4213": "Petugas Penggajian - Golongan 4",
    "4214": "Petugas Statistik dan Keuangan - Golongan 4",
    "4221": "Petugas Perjalanan - Golongan 4",
    "4222": "Resepsionis Hotel - Golongan 4",
    "4223": "Operator Telepon - Golongan 4",
    "4224": "Juru Tamu dan Survei - Golongan 4",
    "4225": "Operator Telepon dan Resepsionis - Golongan 4",
    "4226": "Surveyor dan Pencatat Meter - Golongan 4",
    "4227": "Operator Sentral Telepon - Golongan 4",
    "4229": "Operator Informasi Pelanggan Lainnya - Golongan 4",
    "4311": "Juru Tata Usaha Akuntansi dan Pembukuan - Golongan 4",
    "4312": "Juru Tata Usaha Statistik, Keuangan dan Asuransi - Golongan 4",
    "4313": "Juru Tata Usaha Penggajian - Golongan 4",
    "4321": "Juru Tata Usaha Persediaan - Golongan 4",
    "4322": "Juru Tata Usaha Produksi - Golongan 4",
    "4323": "Juru Tata Usaha Transportasi - Golongan 4",
    "4411": "Petugas Perpustakaan - Golongan 4",
    "4412": "Juru Arsip - Golongan 4",
    "4413": "Petugas Penggajian - Golongan 4",
    "4415": "Petugas Personalia - Golongan 4",
    "4416": "Petugas Administrasi Kantor Lainnya - Golongan 4",
    
    // Golongan 5: Tenaga Usaha Jasa dan Tenaga Penjualan
    "5111": "Pramugara - Golongan 5",
    "5112": "Kondektur Kereta Api - Golongan 5",
    "5113": "Pemandu Wisata - Golongan 5",
    "5120": "Juru Masak - Golongan 5",
    "5131": "Pelayan - Golongan 5",
    "5132": "Bartender - Golongan 5",
    "5141": "Penata Rambut - Golongan 5",
    "5142": "Spesialis Perawatan Kecantikan - Golongan 5",
    "5151": "Pengawas Gedung - Golongan 5",
    "5152": "Pemelihara Rumah Tangga - Golongan 5",
    "5153": "Penjaga Hewan Peliharaan - Golongan 5",
    "5161": "Operator Binatu - Golongan 5",
    "5162": "Pekerja Cuci Kering dan Setrika - Golongan 5",
    "5163": "Penyetrika Pakaian - Golongan 5",
    "5164": "Pekerja Jasa Pemakaman - Golongan 5",
    "5165": "Petugas Pangkas Rambut - Golongan 5",
    "5169": "Pekerja Jasa Pribadi Lainnya - Golongan 5",
    "5211": "Pedagang di Kios dan Warung - Golongan 5",
    "5212": "Pedagang Kaki Lima - Golongan 5",
    "5220": "Tenaga Penjualan di Toko - Golongan 5",
    "5230": "Kasir dan Petugas Penjualan Tiket - Golongan 5",
    "5241": "Peragawan dan Peragawati - Golongan 5",
    "5242": "Demonstrator di Toko dan Pasar - Golongan 5",
    "5243": "Penjual Koran - Golongan 5",
    "5244": "Pengisi Bahan Bakar Kendaraan Bermotor - Golongan 5",
    "5245": "Operator Call Center - Golongan 5",
    "5246": "Penelepon Produk - Golongan 5",
    "5249": "Tenaga Penjualan Lainnya - Golongan 5",
    "5311": "Pengasuh Anak - Golongan 5",
    "5312": "Asisten Guru - Golongan 5",
    "5321": "Perawat Kesehatan Rumah - Golongan 5",
    "5322": "Pembantu Perawat Rumah Sakit - Golongan 5",
    "5329": "Pembantu Perawat Kesehatan Lainnya - Golongan 5",
    "5411": "Petugas Pemadam Kebakaran - Golongan 5",
    "5412": "Polisi - Golongan 5",
    "5413": "Sipir Penjara - Golongan 5",
    "5414": "Satpam - Golongan 5",
    "5419": "Petugas Perlindungan Keamanan Lainnya - Golongan 5",
    
    // Golongan 6: Pekerja Terampil Pertanian, Kehutanan dan Perikanan
    "6111": "Petani Tanaman Pangan - Golongan 6",
    "6112": "Petani Sayuran - Golongan 6",
    "6113": "Petani Perkebunan dan Tanaman Buah - Golongan 6",
    "6114": "Petani Tanaman Perkebunan - Golongan 6",
    "6121": "Peternak Hewan - Golongan 6",
    "6122": "Peternak Unggas - Golongan 6",
    "6123": "Peternak Lebah - Golongan 6",
    "6129": "Peternak Hewan Lainnya - Golongan 6",
    "6130": "Petani Tanaman dan Peternak Hewan - Golongan 6",
    "6210": "Pekerja Kehutanan - Golongan 6",
    "6221": "Pembudidaya Ikan - Golongan 6",
    "6222": "Penangkap Ikan Perairan Darat - Golongan 6",
    "6223": "Penangkap Ikan Perairan Laut - Golongan 6",
    "6224": "Pemburu dan Penjebak Binatang - Golongan 6",
    
    // Golongan 7: Pekerja Pengolahan, Kerajinan, dan YBDI
    "7111": "Pembangun Rumah - Golongan 7",
    "7112": "Tukang Batu - Golongan 7",
    "7113": "Tukang Kayu Beton dan Terkait - Golongan 7",
    "7114": "Tukang Kayu - Golongan 7",
    "7115": "Teknisi Struktural Metal - Golongan 7",
    "7119": "Pekerja Konstruksi Bangunan dan yang Terkait Lainnya - Golongan 7",
    "7121": "Pemasang Atap - Golongan 7",
    "7122": "Pemasang Lantai dan Ubin - Golongan 7",
    "7123": "Tukang Plester - Golongan 7",
    "7124": "Tukang Pengisolasi - Golongan 7",
    "7125": "Tukang Kaca - Golongan 7",
    "7126": "Tukang Pipa - Golongan 7",
    "7127": "Tukang AC dan Pendingin - Golongan 7",
    "7131": "Tukang Cat - Golongan 7",
    "7132": "Tukang Semprot Cat - Golongan 7",
    "7133": "Tukang Bersih Bangunan - Golongan 7",
    "7211": "Tukang Cor Logam - Golongan 7",
    "7212": "Tukang Las - Golongan 7",
    "7213": "Tukang Ketel Uap - Golongan 7",
    "7214": "Pemotong dan Penetap Plat Logam - Golongan 7",
    "7215": "Pekerja Konstruksi Struktural Metal - Golongan 7",
    "7221": "Tukang Pandai Besi dan Pekerja Perkakas - Golongan 7",
    "7222": "Tukang Pembuat Perkakas dan yang Terkait - Golongan 7",
    "7223": "Tukang Penyetel dan Operator Mesin Perkakas - Golongan 7",
    "7224": "Penggosok dan Pekerja Finishing Logam - Golongan 7",
    "7231": "Mekanik dan Reparasi Motor Kendaraan - Golongan 7",
    "7232": "Mekanik dan Reparasi Pesawat Terbang - Golongan 7",
    "7233": "Mekanik dan Reparasi Kapal - Golongan 7",
    "7234": "Mekanik dan Reparasi Sepeda dan yang Terkait - Golongan 7",
    "7311": "Pekerja Tukang Instrumen Presisi - Golongan 7",
    "7312": "Pembuat Alat Musik - Golongan 7",
    "7313": "Pembuat dan Penyetel Perhiasan - Golongan 7",
    "7314": "Tukang Keramik, Tembikar dan yang Terkait - Golongan 7",
    "7315": "Pekerja Tukang Kaca, Penanda dan Pengukir - Golongan 7",
    "7316": "Pembuat Kerajinan Kayu dan yang Terkait - Golongan 7",
    "7317": "Pembuat Kerajinan Tekstil, Kulit dan yang Terkait - Golongan 7",
    "7318": "Pembuat Kerajinan Ukir dan yang Terkait - Golongan 7",
    "7319": "Pekerja Kerajinan Lainnya - Golongan 7",
    "7321": "Tukang Cetak Manual - Golongan 7",
    "7322": "Operator Mesin Cetak - Golongan 7",
    "7323": "Tukang Finishing dan Penjilidan - Golongan 7",
    "7411": "Tukang Listrik Bangunan - Golongan 7",
    "7412": "Tukang Listrik dan Elektronik - Golongan 7",
    "7413": "Tukang Pemasang dan Perbaikan Jalur Listrik - Golongan 7",
    "7421": "Mekanik dan Reparasi Alat Elektronik - Golongan 7",
    "7422": "Teknisi Instalasi dan Reparasi Teknologi Informasi dan Komunikasi - Golongan 7",
    "7511": "Tukang Daging dan Tukang Ikan - Golongan 7",
    "7512": "Tukang Roti, Tukang Kue dan Pembuat Makanan - Golongan 7",
    "7513": "Operator Mesin Produk Susu - Golongan 7",
    "7514": "Pekerja Pengawetan Buah, Sayuran dan yang Terkait - Golongan 7",
    "7515": "Tester dan Pencicip Makanan dan Minuman - Golongan 7",
    "7516": "Tukang Tembakau dan Produk Tembakau - Golongan 7",
    "7521": "Pekerja Penyamakan Kulit - Golongan 7",
    "7522": "Tukang Sepatu dan yang Terkait - Golongan 7",
    "7523": "Tukang Menjahit, Menyulam dan yang Terkait - Golongan 7",
    "7531": "Penjahit - Golongan 7",
    "7532": "Pembuat Pola Garmen - Golongan 7",
    "7533": "Tukang Jahit, Bordir dan yang Terkait - Golongan 7",
    "7534": "Pekerja Pengeleman dan Pelapis Tekstil - Golongan 7",
    "7535": "Penjahit Kulit dan Bulu - Golongan 7",
    "7536": "Pembuat Topi - Golongan 7",
    "7541": "Penyelam - Golongan 7",
    "7542": "Peledak dan Pengebor - Golongan 7",
    "7543": "Operator Produk Karet - Golongan 7",
    "7544": "Operator Produk Plastik - Golongan 7",
    "7549": "Pekerja Kerajinan Lainnya - Golongan 7",
    
    // Golongan 8: Operator dan Perakit Mesin
    "8111": "Operator Instalasi Pertambangan - Golongan 8",
    "8112": "Operator Instalasi Pengolahan Mineral - Golongan 8",
    "8113": "Operator Sumur Minyak dan Gas - Golongan 8",
    "8114": "Operator Instalasi Semen dan Produk Batu - Golongan 8",
    "8121": "Operator Mesin Pengolahan Logam - Golongan 8",
    "8122": "Operator Instalasi Pengolahan Kimia - Golongan 8",
    "8131": "Operator Mesin Produk Kaca dan Keramik - Golongan 8",
    "8132": "Operator Mesin Uap Boiler - Golongan 8",
    "8141": "Operator Mesin Pengolahan Kayu - Golongan 8",
    "8142": "Operator Mesin Pulp dan Kertas - Golongan 8",
    "8143": "Operator Mesin Pengolahan Kimia - Golongan 8",
    "8151": "Operator Mesin Serat - Golongan 8",
    "8152": "Operator Mesin Tenunan dan Rajutan - Golongan 8",
    "8153": "Operator Mesin Jahit - Golongan 8",
    "8154": "Operator Mesin Pemutihan, Pewarnaan dan Pencucian - Golongan 8",
    "8155": "Operator Mesin Kulit - Golongan 8",
    "8156": "Operator Mesin Sepatu - Golongan 8",
    "8157": "Operator Mesin Pencucian Industri - Golongan 8",
    "8159": "Operator Mesin Tekstil, Bulu, Kulit Lainnya - Golongan 8",
    "8160": "Operator Mesin Pengolahan Makanan - Golongan 8",
    "8171": "Operator Mesin Produk Pulp dan Kertas - Golongan 8",
    "8172": "Operator Mesin Produk Kayu - Golongan 8",
    "8181": "Operator Mesin Penggiling dan Pencampur - Golongan 8",
    "8182": "Operator Mesin Kemasan, Pembotolan dan Pelabelan - Golongan 8",
    "8183": "Operator Mesin Cetak - Golongan 8",
    "8189": "Operator Mesin Produk Statis Lainnya - Golongan 8",
    "8211": "Perakit Mesin - Golongan 8",
    "8212": "Perakit Produk Logam, Karet dan Plastik - Golongan 8",
    "8219": "Perakit Lainnya - Golongan 8",
    "8311": "Masinis Lokomotif - Golongan 8",
    "8312": "Operator Rel Kereta - Golongan 8",
    "8321": "Pengemudi Motor - Golongan 8",
    "8322": "Pengemudi Mobil, Taksi dan Van - Golongan 8",
    "8331": "Pengemudi Bus dan Trem - Golongan 8",
    "8332": "Pengemudi Truk Berat - Golongan 8",
    "8341": "Operator Alat Berat Pertanian dan Kehutanan - Golongan 8",
    "8342": "Operator Alat Berat Pertambangan dan Konstruksi - Golongan 8",
    "8343": "Operator Crane, Derek dan Alat Pengangkat Lainnya - Golongan 8",
    "8344": "Operator Forklift - Golongan 8",
    "8350": "Awak Kapal dan yang Terkait - Golongan 8",
    
    // Golongan 9: Pekerja Kasar
    "9111": "Pembersih Rumah dan Kantor - Golongan 9",
    "9112": "Pembersih Kendaraan dan Jendela - Golongan 9",
    "9113": "Pencuci Tangan - Golongan 9",
    "9121": "Pencuci Piring - Golongan 9",
    "9122": "Pekerja Dapur - Golongan 9",
    "9123": "Tukang Cuci Setrika Manual - Golongan 9",
    "9129": "Pekerja Penyedia Makanan Lainnya - Golongan 9",
    "9211": "Pekerja Kasar Pertanian, Kehutanan dan Perikanan - Golongan 9",
    "9212": "Pekerja Kasar Pertambangan dan Konstruksi - Golongan 9",
    "9213": "Pekerja Kasar Industri Pengolahan - Golongan 9",
    "9214": "Pekerja Kasar Transportasi dan Pergudangan - Golongan 9",
    "9215": "Pekerja Kasar Pengumpul Sampah - Golongan 9",
    "9216": "Pekerja Kasar Lainnya - Golongan 9",
    "9311": "Pekerja Penambang Manual - Golongan 9",
    "9312": "Pekerja Pembuatan Batu Bata - Golongan 9",
    "9313": "Pekerja Pemotong Batu - Golongan 9",
    "9321": "Pekerja Perakitan Manual Produk Sederhana - Golongan 9",
    "9329": "Pekerja Perakitan Manual Lainnya - Golongan 9",
    "9331": "Pengangkut Barang Manual - Golongan 9",
    "9332": "Pekerja Pengemudi Becak dan Sejenisnya - Golongan 9",
    "9333": "Kusir Kendaraan Bertenaga Hewan - Golongan 9",
    "9334": "Pekerja Pemindah Barang dan Terkait - Golongan 9",
    "9411": "Penjual Makanan Cepat Saji - Golongan 9",
    "9412": "Penjaja Keliling - Golongan 9",
    "9510": "Pekerja Kasar Petugas Kebersihan Jalan - Golongan 9",
    "9520": "Pekerja Kasar Penyortir Sampah - Golongan 9",
    "9611": "Pengumpul Sampah - Golongan 9",
    "9612": "Penyortir Sampah - Golongan 9",
    "9613": "Penyapu Jalan dan yang Terkait - Golongan 9",
    "9621": "Pembawa Pesan dan Portir - Golongan 9",
    "9622": "Pekerja Meteran dan Vending Machine - Golongan 9",
    "9623": "Pembawa Air dan Pengumpul Kayu Bakar - Golongan 9",
    "9624": "Pekerja Pengisi dan Pengemasan - Golongan 9",
    "9629": "Pekerja Kasar Lainnya - Golongan 9",
  },
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { query } = await req.json();
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    console.log("Processing query:", query);

    // Create knowledge base for AI
    const knowledgeBase = `
Anda adalah AI Agent klasifikasi SAKERNAS BPS 2025. Database Anda mencakup:

LAPANGAN USAHA (KBLI 2020):
${Object.entries(SAKERNAS_DB.lapanganUsaha).map(([code, desc]) => `- ${code}: ${desc}`).join('\n')}

JENIS PEKERJAAN (KBJI 2014):
${Object.entries(SAKERNAS_DB.jenisPekerjaan).map(([code, desc]) => `- ${code}: ${desc}`).join('\n')}

Tugas Anda:
1. Identifikasi kategori dari query user (lapangan usaha, pekerjaan, atau keduanya)
2. Cari kode yang paling sesuai dari database
3. Berikan jawaban dalam format tabel markdown
4. Berikan penjelasan singkat

Format respons WAJIB menggunakan tabel markdown seperti ini:

| Aspek | Kode | Keterangan |
|-------|------|------------|
| Lapangan Usaha | [kode] | [deskripsi lengkap] |
| Jenis Pekerjaan | [kode] | [deskripsi lengkap] |

Kemudian berikan penjelasan singkat dan tanyakan: "Apakah Anda membutuhkan informasi lebih lanjut?"
`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: knowledgeBase },
          { role: "user", content: query },
        ],
        temperature: 0.3,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit tercapai. Silakan coba lagi sebentar." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "Kredit AI habis. Silakan tambah kredit di workspace Anda." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      throw new Error("AI gateway error");
    }

    const data = await response.json();
    console.log("AI response received successfully");

    return new Response(
      JSON.stringify({ 
        result: data.choices[0].message.content 
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error) {
    console.error("Error in classify-sakernas:", error);
    const errorMessage = error instanceof Error ? error.message : "Terjadi kesalahan";
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
